/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseAlert: typeof import('./src/components/base/BaseAlert.vue')['default']
    BaseBtn: typeof import('./src/components/base/BaseBtn.vue')['default']
    BaseForm: typeof import('./src/components/base/BaseForm.vue')['default']
    BaseFormItem: typeof import('./src/components/base/BaseFormItem.vue')['default']
    BaseInput: typeof import('./src/components/base/BaseInput.vue')['default']
    BaseInputNumber: typeof import('./src/components/base/BaseInputNumber.vue')['default']
    Icon: typeof import('./src/components/common/Icon.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/layout/SideBar.vue')['default']
  }
}
